version: "3"

volumes:
  zkmultiple-kmultiple_kafka1-data:
  zkmultiple-kmultiple_kafka2-data:
  zkmultiple-kmultiple_kafka3-data:
  zkmultiple-kmultiple_zoo1-data:
  zkmultiple-kmultiple_zoo2-data:
  zkmultiple-kmultiple_zoo3-data:
  zkmultiple-kmultiple_zoo1-log:
  zkmultiple-kmultiple_zoo2-log:
  zkmultiple-kmultiple_zoo3-log:

services:

  client:
    build: ./client_repo
    container_name: mars_subscriber 
    image: mars_subscriber
    ports:
      - 5081:8003
    networks:
      - mars_network
    depends_on:
      - kafka1

  publisher1:
    build: ./publisher_repo1
    container_name: mars_publisher1
    image: mars_publisher1
    ports:
      - 5051:8001
    networks:
      - mars_network
    depends_on:
      - kafka1

  publisher2:
    build: ./publisher_repo2
    container_name: mars_publisher2
    image: mars_publisher2
    ports:
      - 5052:8001
    networks:
      - mars_network

  publisher3:
    build: ./publisher_repo3
    container_name: mars_publisher3
    image: mars_publisher3
    ports:
      - 5053:8001
    networks:
      - mars_network

  database1:
    platform: linux/x86_64
    image: mysql:5.7
    ports:
      - "5071:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db1/data1:/var/lib/mysql
      - ./database1/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mars_network

  server1:
    build: ./server_repo1
    image: mars_broker1
    container_name: mars_broker1
    ports:
      - 5061:8002
    depends_on: 
      - database1
    networks:
      - mars_network

  zoo1:
    image: 'bitnami/zookeeper:latest'
    container_name: zoo1
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOOKEEPER_CLIENT_PORT:2181
      - ZOOKEEPER_SERVER_ID:1
      - ZOOKEEPER_SERVERS:zoo1:2888:3888;zoo2:2888:3888;zoo3:2888:3888
    networks:
      - mars_network

  zoo2:
    image: 'bitnami/zookeeper:latest'
    container_name: zoo2
    ports:
      - '2182:2182'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOOKEEPER_CLIENT_PORT:2182
      - ZOOKEEPER_SERVER_ID:2
      - ZOOKEEPER_SERVERS:zoo1:2888:3888;zoo2:2888:3888;zoo3:2888:3888
    networks:
      - mars_network

  zoo3:
    image: 'bitnami/zookeeper:latest'
    container_name: zoo3
    ports:
      - '2183:2183'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOOKEEPER_CLIENT_PORT:2183
      - ZOOKEEPER_SERVER_ID:3
      - ZOOKEEPER_SERVERS:zoo1:2888:3888;zoo2:2888:3888;zoo3:2888:3888
    networks:
      - mars_network

  kafka1:
    image: 'bitnami/kafka:latest'
    container_name: kakfa1
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP:LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME:LISTENER_DOCKER_INTERNAL
      - KAFKA_ZOOKEEPER_CONNECT=zoo1:2181,zoo2:2182,zoo3:2183
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    networks:
      - mars_network

  kafka2:
    image: 'bitnami/kafka:latest'
    container_name: kakfa2
    ports:
      - '9093:9093'
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_LISTENERS=PLAINTEXT://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka2:9093
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP:LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME:LISTENER_DOCKER_INTERNAL
      - KAFKA_ZOOKEEPER_CONNECT=zoo1:2181,zoo2:2182,zoo3:2183
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    networks:
      - mars_network

  kafka3:
    image: 'bitnami/kafka:latest'
    container_name: kakfa3
    ports:
      - '9094:9094'
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_LISTENERS=PLAINTEXT://:9094
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka3:9094
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP:LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME:LISTENER_DOCKER_INTERNAL
      - KAFKA_ZOOKEEPER_CONNECT=zoo1:2181,zoo2:2182,zoo3:2183
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    networks:
      - mars_network

networks: 
  mars_network:
    name: mars_network
    driver : bridge